// <auto-generated />
using System;
using GeoVolt.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoVolt.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GeoVoltDbContext))]
    [Migration("20260719092127_AddSuitabilityMetricWorkflow")]
    partial class AddSuitabilityMetricWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoVolt.Domain.Entities.CandidatePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccessScore")
                        .HasColumnType("integer");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CompetitionPenalty")
                        .HasColumnType("integer");

                    b.Property<int?>("CostScore")
                        .HasColumnType("integer");

                    b.Property<int?>("DemandScore")
                        .HasColumnType("integer");

                    b.Property<int?>("EnergyScore")
                        .HasColumnType("integer");

                    b.Property<string>("EstimatedAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("EstimatedCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("GeneralScore")
                        .HasColumnType("integer");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<double?>("NearestMajorRoadMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("NearestStationMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("NearestTransformerMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("NeighborhoodId")
                        .HasColumnType("integer");

                    b.Property<string>("PlaceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("PoiCount1000Meters")
                        .HasColumnType("integer");

                    b.Property<int?>("PoiCount300Meters")
                        .HasColumnType("integer");

                    b.Property<int?>("PoiCount500Meters")
                        .HasColumnType("integer");

                    b.Property<int?>("Population")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("SuitabilityDegree")
                        .HasColumnType("double precision");

                    b.Property<double?>("SuitabilityPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("SystemType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmVersion");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("RegionId", "NeighborhoodId");

                    b.HasIndex("Status", "GeneralScore");

                    b.ToTable("candidate_points", "analysis");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.ChargingConnector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChargingStationId")
                        .HasColumnType("integer")
                        .HasColumnName("charging_station_id");

                    b.Property<string>("ConnectorType")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("connector_type");

                    b.Property<double>("PowerKw")
                        .HasColumnType("double precision")
                        .HasColumnName("power_kw");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("SocketType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("socket_type");

                    b.Property<string>("SourceSocketNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_socket_number");

                    b.HasKey("Id");

                    b.HasIndex("ChargingStationId", "SourceSocketNumber")
                        .IsUnique();

                    b.ToTable("charging_connectors", "gis");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.ChargingStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("access_type");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("BrandName")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("brand_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool?>("IsGreenStation")
                        .HasColumnType("boolean")
                        .HasColumnName("is_green_station");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("name");

                    b.Property<int>("NeighborhoodId")
                        .HasColumnType("integer")
                        .HasColumnName("neighborhood_id");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("operator_name");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.Property<string>("SourceStationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_station_number");

                    b.HasKey("Id");

                    b.HasIndex("AccessType");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("NeighborhoodId");

                    b.HasIndex("OperatorName");

                    b.HasIndex("RegionId");

                    b.HasIndex("SourceStationNumber")
                        .IsUnique();

                    b.ToTable("charging_stations", "gis");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("contact_email");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tax_number");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.CostModelSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<decimal>("RoundingStep")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("rounding_step");

                    b.Property<decimal>("RouteMultiplier")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("route_multiplier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("cost_model_settings", "costing", t =>
                        {
                            t.HasCheckConstraint("ck_cost_model_settings_currency_code", "char_length(currency_code) = 3");

                            t.HasCheckConstraint("ck_cost_model_settings_rounding_step", "rounding_step > 0");

                            t.HasCheckConstraint("ck_cost_model_settings_route_multiplier", "route_multiplier > 0");

                            t.HasCheckConstraint("ck_cost_model_settings_single_row", "id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrencyCode = "TRY",
                            RoundingStep = 1000.00m,
                            RouteMultiplier = 1.150m,
                            UpdatedAtUtc = new DateTime(2026, 7, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = "2026.1"
                        });
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.CostProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CableUnitCostPerMeter")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cable_unit_cost_per_meter");

                    b.Property<decimal>("EquipmentCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("equipment_cost");

                    b.Property<decimal>("FixedElectricalInfrastructureCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("fixed_electrical_infrastructure_cost");

                    b.Property<decimal>("FixedSiteCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("fixed_site_cost");

                    b.Property<int>("PowerKw")
                        .HasColumnType("integer")
                        .HasColumnName("power_kw");

                    b.Property<decimal>("RiskRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("risk_rate");

                    b.Property<string>("SystemType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("system_type");

                    b.Property<decimal>("TrenchRestorationUnitCostPerMeter")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("trench_restoration_unit_cost_per_meter");

                    b.HasKey("Id");

                    b.HasIndex("SystemType", "PowerKw")
                        .IsUnique()
                        .HasDatabaseName("uq_cost_profiles_system_type_power_kw");

                    b.ToTable("cost_profiles", "costing", t =>
                        {
                            t.HasCheckConstraint("ck_cost_profiles_cable_cost", "cable_unit_cost_per_meter >= 0");

                            t.HasCheckConstraint("ck_cost_profiles_equipment_cost", "equipment_cost >= 0");

                            t.HasCheckConstraint("ck_cost_profiles_fixed_electrical_cost", "fixed_electrical_infrastructure_cost >= 0");

                            t.HasCheckConstraint("ck_cost_profiles_fixed_site_cost", "fixed_site_cost >= 0");

                            t.HasCheckConstraint("ck_cost_profiles_power_kw", "power_kw > 0");

                            t.HasCheckConstraint("ck_cost_profiles_risk_rate", "risk_rate >= 0 AND risk_rate <= 1");

                            t.HasCheckConstraint("ck_cost_profiles_system_type", "system_type IN ('AC', 'DC')");

                            t.HasCheckConstraint("ck_cost_profiles_trench_cost", "trench_restoration_unit_cost_per_meter >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CableUnitCostPerMeter = 761.00m,
                            EquipmentCost = 44300.00m,
                            FixedElectricalInfrastructureCost = 50000.00m,
                            FixedSiteCost = 25000.00m,
                            PowerKw = 22,
                            RiskRate = 0.1000m,
                            SystemType = "AC",
                            TrenchRestorationUnitCostPerMeter = 1500.00m
                        },
                        new
                        {
                            Id = 2,
                            CableUnitCostPerMeter = 3181.00m,
                            EquipmentCost = 700000.00m,
                            FixedElectricalInfrastructureCost = 200000.00m,
                            FixedSiteCost = 40000.00m,
                            PowerKw = 60,
                            RiskRate = 0.1500m,
                            SystemType = "DC",
                            TrenchRestorationUnitCostPerMeter = 1700.00m
                        },
                        new
                        {
                            Id = 3,
                            CableUnitCostPerMeter = 5353.00m,
                            EquipmentCost = 1200000.00m,
                            FixedElectricalInfrastructureCost = 350000.00m,
                            FixedSiteCost = 50000.00m,
                            PowerKw = 120,
                            RiskRate = 0.1500m,
                            SystemType = "DC",
                            TrenchRestorationUnitCostPerMeter = 1700.00m
                        });
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.DatasetCoverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompletenessStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("completeness_status");

                    b.Property<MultiPolygon>("CoverageGeometry")
                        .HasColumnType("geometry (MultiPolygon, 4326)")
                        .HasColumnName("coverage_geometry");

                    b.Property<string>("CoverageStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("coverage_status");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DatasetImportId")
                        .HasColumnType("integer")
                        .HasColumnName("dataset_import_id");

                    b.Property<bool>("IsAuthoritative")
                        .HasColumnType("boolean")
                        .HasColumnName("is_authoritative");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<decimal?>("QualityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("quality_score");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CoverageGeometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CoverageGeometry"), "gist");

                    b.HasIndex("DatasetImportId")
                        .IsUnique();

                    b.HasIndex("CoverageStatus", "CompletenessStatus");

                    b.ToTable("dataset_coverages", "gis", t =>
                        {
                            t.HasCheckConstraint("ck_dataset_coverages_completeness_status", "completeness_status IN ('Unknown', 'Partial', 'Complete')");

                            t.HasCheckConstraint("ck_dataset_coverages_coverage_status", "coverage_status IN ('Unknown', 'Declared', 'Verified')");

                            t.HasCheckConstraint("ck_dataset_coverages_geometry_required", "coverage_status = 'Unknown' OR coverage_geometry IS NOT NULL");

                            t.HasCheckConstraint("ck_dataset_coverages_quality_score", "quality_score IS NULL OR (quality_score >= 0 AND quality_score <= 100)");
                        });
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.DatasetImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DatasetName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("FeatureCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("SourceDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("SourceSrid")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TargetSrid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.HasIndex("DatasetName", "ImportedAtUtc");

                    b.ToTable("dataset_imports", "gis");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Geometry>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry (MultiPolygon, 4326)")
                        .HasColumnName("boundary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<int?>("Population")
                        .HasColumnType("integer")
                        .HasColumnName("population");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.HasKey("Id");

                    b.HasIndex("Boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "gist");

                    b.HasIndex("Name");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("districts", "gis");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.Neighborhood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Geometry>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry (MultiPolygon, 4326)")
                        .HasColumnName("boundary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<int>("Population")
                        .HasColumnType("integer")
                        .HasColumnName("population");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.HasKey("Id");

                    b.HasIndex("Boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "gist");

                    b.HasIndex("Name");

                    b.HasIndex("RegionId");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("neighborhoods", "gis");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.Poi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Phone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Website")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.HasIndex("Category", "SubCategory");

                    b.ToTable("pois", "gis");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.PowerTransformer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint");

                    b.Property<string>("TransformerType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.HasIndex("TransformerType");

                    b.ToTable("power_transformers", "gis");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Geometry>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry (MultiPolygon, 4326)")
                        .HasColumnName("boundary");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("district_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<int>("Population")
                        .HasColumnType("integer")
                        .HasColumnName("population");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.HasKey("Id");

                    b.HasIndex("Boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "gist");

                    b.HasIndex("DistrictId");

                    b.HasIndex("Name");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("regions", "gis");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.Road", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageSpeed")
                        .HasColumnType("double precision");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry (MultiLineString, 4326)");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("RoadType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("RoadType");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("roads", "gis");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.SavedCandidatePoint", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("CandidatePointId")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_point_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.HasKey("UserId", "CandidatePointId");

                    b.ToTable("saved_candidate_points", (string)null);
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.ScoringProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccessWeight")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal>("CompetitionWeight")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DemandWeight")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal>("EnergyWeight")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("scoring_profiles", "analysis");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.SlopeCostBand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ExtraRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("extra_rate");

                    b.Property<decimal?>("MaxSlopePercent")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("max_slope_percent");

                    b.Property<decimal>("MinSlopePercent")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("min_slope_percent");

                    b.HasKey("Id");

                    b.HasIndex("MinSlopePercent")
                        .IsUnique()
                        .HasDatabaseName("uq_slope_cost_bands_minimum");

                    b.ToTable("slope_cost_bands", "costing", t =>
                        {
                            t.HasCheckConstraint("ck_slope_cost_bands_extra_rate", "extra_rate >= 0 AND extra_rate <= 1");

                            t.HasCheckConstraint("ck_slope_cost_bands_maximum", "max_slope_percent IS NULL OR max_slope_percent > min_slope_percent");

                            t.HasCheckConstraint("ck_slope_cost_bands_minimum", "min_slope_percent >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExtraRate = 0.0000m,
                            MaxSlopePercent = 3.00m,
                            MinSlopePercent = 0.00m
                        },
                        new
                        {
                            Id = 2,
                            ExtraRate = 0.0500m,
                            MaxSlopePercent = 6.00m,
                            MinSlopePercent = 3.00m
                        },
                        new
                        {
                            Id = 3,
                            ExtraRate = 0.1200m,
                            MaxSlopePercent = 10.00m,
                            MinSlopePercent = 6.00m
                        },
                        new
                        {
                            Id = 4,
                            ExtraRate = 0.2500m,
                            MaxSlopePercent = 15.00m,
                            MinSlopePercent = 10.00m
                        },
                        new
                        {
                            Id = 5,
                            ExtraRate = 0.4000m,
                            MinSlopePercent = 15.00m
                        });
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.StagedGeoJsonFeature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DatasetImportId")
                        .HasColumnType("integer");

                    b.Property<int>("FeatureIndex")
                        .HasColumnType("integer");

                    b.Property<string>("GeometryJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("GeometryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PropertiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceFeatureId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DatasetImportId", "FeatureIndex")
                        .IsUnique();

                    b.HasIndex("DatasetImportId", "SourceFeatureId");

                    b.ToTable("geojson_features", "staging");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.SuitabilityAnalysisRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("algorithm_version");

                    b.Property<int>("CandidateCellCount")
                        .HasColumnType("integer")
                        .HasColumnName("candidate_cell_count");

                    b.Property<int>("CellCount")
                        .HasColumnType("integer")
                        .HasColumnName("cell_count");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DatasetSnapshotJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("dataset_snapshot")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<int>("GridEdgeMeters")
                        .HasColumnType("integer")
                        .HasColumnName("grid_edge_meters");

                    b.Property<int>("MetricSrid")
                        .HasColumnType("integer")
                        .HasColumnName("metric_srid");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int?>("ScoringProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("scoring_profile_id");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("StorageSrid")
                        .HasColumnType("integer")
                        .HasColumnName("storage_srid");

                    b.Property<int>("StudyAreaDistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("study_area_district_id");

                    b.HasKey("Id");

                    b.HasIndex("ScoringProfileId")
                        .HasDatabaseName("ix_analysis_runs_scoring_profile");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_analysis_runs_status_created");

                    b.HasIndex("StudyAreaDistrictId", "CreatedAtUtc")
                        .HasDatabaseName("ix_analysis_runs_district_created");

                    b.ToTable("analysis_runs", "analysis", t =>
                        {
                            t.HasCheckConstraint("ck_analysis_runs_candidate_cell_count", "candidate_cell_count >= 0 AND candidate_cell_count <= cell_count");

                            t.HasCheckConstraint("ck_analysis_runs_cell_count", "cell_count >= 0");

                            t.HasCheckConstraint("ck_analysis_runs_grid_edge", "grid_edge_meters > 0");

                            t.HasCheckConstraint("ck_analysis_runs_metric_srid", "metric_srid > 0");

                            t.HasCheckConstraint("ck_analysis_runs_status", "status IN ('Pending', 'Running', 'GridReady', 'MetricsReady', 'Completed', 'Failed', 'Cancelled')");

                            t.HasCheckConstraint("ck_analysis_runs_storage_srid", "storage_srid > 0");

                            t.HasCheckConstraint("ck_analysis_runs_time_order", "completed_at_utc IS NULL OR started_at_utc IS NULL OR completed_at_utc >= started_at_utc");
                        });
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.SuitabilityCell", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AnalysisRunId")
                        .HasColumnType("integer")
                        .HasColumnName("analysis_run_id");

                    b.Property<double>("AreaSquareMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("area_square_meters");

                    b.Property<MultiPolygon>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry (MultiPolygon, 4326)")
                        .HasColumnName("boundary");

                    b.Property<DateTime?>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at_utc");

                    b.Property<int>("CellI")
                        .HasColumnType("integer")
                        .HasColumnName("cell_i");

                    b.Property<int>("CellJ")
                        .HasColumnType("integer")
                        .HasColumnName("cell_j");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("confidence_score");

                    b.Property<decimal?>("EstimatedCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("estimated_cost");

                    b.Property<string>("EvaluationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("evaluation_status");

                    b.Property<bool>("HasHardExclusion")
                        .HasColumnType("boolean")
                        .HasColumnName("has_hard_exclusion");

                    b.Property<string>("MetricDetailsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metric_details")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<double?>("NearestMajorRoadMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("nearest_major_road_meters");

                    b.Property<double?>("NearestStationMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("nearest_station_meters");

                    b.Property<double?>("NearestTransformerMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("nearest_transformer_meters");

                    b.Property<int?>("NeighborhoodId")
                        .HasColumnType("integer")
                        .HasColumnName("neighborhood_id");

                    b.Property<int?>("PoiCount1000Meters")
                        .HasColumnType("integer")
                        .HasColumnName("poi_count_1000_meters");

                    b.Property<int?>("PoiCount300Meters")
                        .HasColumnType("integer")
                        .HasColumnName("poi_count_300_meters");

                    b.Property<int?>("PoiCount500Meters")
                        .HasColumnType("integer")
                        .HasColumnName("poi_count_500_meters");

                    b.Property<double?>("PopulationDensityPerSquareKilometer")
                        .HasColumnType("double precision")
                        .HasColumnName("population_density_per_square_kilometer");

                    b.Property<string>("ReasonCodesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("reason_codes")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.Property<Point>("RepresentativePoint")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)")
                        .HasColumnName("representative_point");

                    b.Property<decimal?>("SlopePercent")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("slope_percent");

                    b.Property<decimal?>("SuitabilityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("suitability_score");

                    b.HasKey("Id");

                    b.HasIndex("Boundary")
                        .HasDatabaseName("gist_suitability_cells_boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "gist");

                    b.HasIndex("NeighborhoodId")
                        .HasDatabaseName("ix_suitability_cells_neighborhood");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_suitability_cells_region");

                    b.HasIndex("RepresentativePoint")
                        .HasDatabaseName("gist_suitability_cells_representative_point");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RepresentativePoint"), "gist");

                    b.HasIndex("AnalysisRunId", "CellI", "CellJ")
                        .IsUnique()
                        .HasDatabaseName("uq_suitability_cells_run_grid");

                    b.HasIndex("AnalysisRunId", "EvaluationStatus", "SuitabilityScore")
                        .HasDatabaseName("ix_suitability_cells_run_status_score");

                    b.HasIndex("AnalysisRunId", "RegionId", "NeighborhoodId")
                        .HasDatabaseName("ix_suitability_cells_run_region_neighborhood");

                    b.ToTable("suitability_cells", "analysis", t =>
                        {
                            t.HasCheckConstraint("ck_suitability_cells_area", "area_square_meters > 0");

                            t.HasCheckConstraint("ck_suitability_cells_boundary_valid", "NOT ST_IsEmpty(boundary) AND ST_IsValid(boundary)");

                            t.HasCheckConstraint("ck_suitability_cells_confidence_score", "confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 100)");

                            t.HasCheckConstraint("ck_suitability_cells_distances", "(nearest_transformer_meters IS NULL OR nearest_transformer_meters >= 0) AND (nearest_major_road_meters IS NULL OR nearest_major_road_meters >= 0) AND (nearest_station_meters IS NULL OR nearest_station_meters >= 0)");

                            t.HasCheckConstraint("ck_suitability_cells_estimated_cost", "estimated_cost IS NULL OR estimated_cost >= 0");

                            t.HasCheckConstraint("ck_suitability_cells_evaluation_status", "evaluation_status IN ('OUTSIDE_STUDY_AREA', 'INSUFFICIENT_DATA', 'HARD_EXCLUSION', 'LOW_SUITABILITY', 'CANDIDATE')");

                            t.HasCheckConstraint("ck_suitability_cells_poi_counts", "(poi_count_300_meters IS NULL OR poi_count_300_meters >= 0) AND (poi_count_500_meters IS NULL OR poi_count_500_meters >= 0) AND (poi_count_1000_meters IS NULL OR poi_count_1000_meters >= 0)");

                            t.HasCheckConstraint("ck_suitability_cells_population_density", "population_density_per_square_kilometer IS NULL OR population_density_per_square_kilometer >= 0");

                            t.HasCheckConstraint("ck_suitability_cells_representative_point", "ST_Covers(boundary, representative_point)");

                            t.HasCheckConstraint("ck_suitability_cells_slope", "slope_percent IS NULL OR slope_percent >= 0");

                            t.HasCheckConstraint("ck_suitability_cells_suitability_score", "suitability_score IS NULL OR (suitability_score >= 0 AND suitability_score <= 100)");
                        });
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.UserPermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("user_permissions", (string)null);
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.VenueCostMultiplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Multiplier")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("multiplier");

                    b.Property<string>("VenueType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("venue_type");

                    b.HasKey("Id");

                    b.HasIndex("VenueType")
                        .IsUnique()
                        .HasDatabaseName("uq_venue_cost_multipliers_venue_type");

                    b.ToTable("venue_cost_multipliers", "costing", t =>
                        {
                            t.HasCheckConstraint("ck_venue_cost_multipliers_multiplier", "multiplier > 0");

                            t.HasCheckConstraint("ck_venue_cost_multipliers_name", "length(trim(venue_type)) > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Multiplier = 1.0000m,
                            VenueType = "Workplace"
                        },
                        new
                        {
                            Id = 2,
                            Multiplier = 1.0800m,
                            VenueType = "Mall"
                        },
                        new
                        {
                            Id = 3,
                            Multiplier = 1.1500m,
                            VenueType = "Highway"
                        });
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.ChargingConnector", b =>
                {
                    b.HasOne("GeoVolt.Domain.Entities.ChargingStation", "ChargingStation")
                        .WithMany("Connectors")
                        .HasForeignKey("ChargingStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingStation");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.ChargingStation", b =>
                {
                    b.HasOne("GeoVolt.Domain.Entities.Neighborhood", "Neighborhood")
                        .WithMany("ChargingStations")
                        .HasForeignKey("NeighborhoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeoVolt.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Neighborhood");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.DatasetCoverage", b =>
                {
                    b.HasOne("GeoVolt.Domain.Entities.DatasetImport", "DatasetImport")
                        .WithOne("Coverage")
                        .HasForeignKey("GeoVolt.Domain.Entities.DatasetCoverage", "DatasetImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatasetImport");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.Neighborhood", b =>
                {
                    b.HasOne("GeoVolt.Domain.Entities.Region", "Region")
                        .WithMany("Neighborhoods")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.Region", b =>
                {
                    b.HasOne("GeoVolt.Domain.Entities.District", "District")
                        .WithMany("Regions")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("GeoVolt.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoVolt.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.SavedCandidatePoint", b =>
                {
                    b.HasOne("GeoVolt.Domain.Entities.User", "User")
                        .WithMany("SavedCandidatePoints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.StagedGeoJsonFeature", b =>
                {
                    b.HasOne("GeoVolt.Domain.Entities.DatasetImport", "DatasetImport")
                        .WithMany("StagedFeatures")
                        .HasForeignKey("DatasetImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatasetImport");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.SuitabilityAnalysisRun", b =>
                {
                    b.HasOne("GeoVolt.Domain.Entities.ScoringProfile", "ScoringProfile")
                        .WithMany()
                        .HasForeignKey("ScoringProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GeoVolt.Domain.Entities.District", "StudyAreaDistrict")
                        .WithMany()
                        .HasForeignKey("StudyAreaDistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScoringProfile");

                    b.Navigation("StudyAreaDistrict");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.SuitabilityCell", b =>
                {
                    b.HasOne("GeoVolt.Domain.Entities.SuitabilityAnalysisRun", "AnalysisRun")
                        .WithMany("Cells")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoVolt.Domain.Entities.Neighborhood", "Neighborhood")
                        .WithMany()
                        .HasForeignKey("NeighborhoodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GeoVolt.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AnalysisRun");

                    b.Navigation("Neighborhood");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.User", b =>
                {
                    b.HasOne("GeoVolt.Domain.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.UserPermission", b =>
                {
                    b.HasOne("GeoVolt.Domain.Entities.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoVolt.Domain.Entities.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("GeoVolt.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoVolt.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.ChargingStation", b =>
                {
                    b.Navigation("Connectors");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.Company", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.DatasetImport", b =>
                {
                    b.Navigation("Coverage");

                    b.Navigation("StagedFeatures");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.District", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.Neighborhood", b =>
                {
                    b.Navigation("ChargingStations");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.Region", b =>
                {
                    b.Navigation("Neighborhoods");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.SuitabilityAnalysisRun", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("GeoVolt.Domain.Entities.User", b =>
                {
                    b.Navigation("SavedCandidatePoints");

                    b.Navigation("UserPermissions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
