using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GeoVolt.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddSlopeRasterStorage : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("CREATE EXTENSION IF NOT EXISTS postgis_raster;");

            migrationBuilder.Sql(
                """
                CREATE TABLE gis.slope_raster_tiles (
                    rid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    rast raster NOT NULL,
                    filename text NOT NULL,
                    sha256 character varying(64),
                    source_srid integer NOT NULL DEFAULT 32636,
                    imported_at_utc timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT ck_slope_raster_tiles_source_srid CHECK (source_srid = 32636)
                );

                CREATE INDEX gist_slope_raster_tiles_convex_hull
                    ON gis.slope_raster_tiles
                    USING gist (ST_ConvexHull(rast));
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS gis.slope_raster_tiles;");
        }
    }
}
